# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/bionic64'
  config.vm.box_check_update = true

  config.vm.network 'forwarded_port', guest: '3306', host: '3306',
                                      host_ip: '127.0.0.1'

  config.vm.synced_folder '..', '/vagrant', owner: 'vagrant',
                                            group: 'vagrant'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"| tee /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get install -y docker-ce
    apt-get dist-upgrade -y
    curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    usermod -aG docker vagrant
  SHELL
end
